# workflow name
name: release

# on events
# on:
#   release:
#     types:
#       - created
on:
    push:
        tags:
            - 'v*.*.*'

# jobs
jobs:
  # generate build cross-platform build files
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      # step 1: checkout repository code
      - name: Checkout the repository
        uses: actions/checkout@v2

      # step 2: generate build files
      - name: Generate build files
        uses: thatisuday/go-build-action@v1
        with:
          platforms: "darwin/amd64, darwin/arm64, linux/amd64, windows/amd64"
          name: "release-test"
          compress: "true"
          dest: "dist"

    #   # step 3: upload build-artifacts
    #   - name: Upload build-artifacts
    #     uses: skx/github-action-publish-binaries@master
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     with:
    #       args: "./dist/*.tar.gz"
